var aObjectType = 
[
    {"id" : "0", "name" : "Улица", "short_name" : "ул.", "type" : "0"},
    {"id" : "1", "name" : "Государство", "short_name" : "Гос-во", "type" : "0"},
    {"id" : "2", "name" : "Федеральный округ", "short_name" : "ФО", "type" : "1"},
    {"id" : "3", "name" : "Автономный округ", "short_name" : "АО", "type" : "1"},
    {"id" : "4", "name" : "Автономная область", "short_name" : "Аобл", "type" : "1"},
    {"id" : "5", "name" : "Город", "short_name" : "г.", "type" : "0"},
    {"id" : "6", "name" : "Край", "short_name" : "край", "type" : "1"},
    {"id" : "7", "name" : "Область", "short_name" : "обл.", "type" : "1"},
    {"id" : "8", "name" : "Республика", "short_name" : "Респ", "type" : "0"},
    {"id" : "9", "name" : "Округ", "short_name" : "округ", "type" : "1"},
    {"id" : "10", "name" : "Район", "short_name" : "р-н", "type" : "1"},
    {"id" : "11", "name" : "Улус", "short_name" : "у", "type" : "1"},
    {"id" : "12", "name" : "Территория", "short_name" : "тер.", "type" : "1"},
    {"id" : "13", "name" : "Поселок городского типа", "short_name" : "пгт.", "type" : "0"},
    {"id" : "14", "name" : "Рабочий поселок", "short_name" : "рп.", "type" : "0"},
    {"id" : "15", "name" : "Курортный поселок", "short_name" : "кп.", "type" : "0"},
    {"id" : "16", "name" : "Дачный поселок", "short_name" : "дп", "type" : "0"},
    {"id" : "17", "name" : "Сельсовет", "short_name" : "с/с", "type" : "0"},
    {"id" : "18", "name" : "Сельская администрация", "short_name" : "с/а", "type" : "0"},
    {"id" : "19", "name" : "Сельский округ", "short_name" : "с/о", "type" : "1"},
    {"id" : "20", "name" : "Волость", "short_name" : "волость", "type" : "1"},
    {"id" : "21", "name" : "Почтовое отделение", "short_name" : "п/о", "type" : "0"},
    {"id" : "22", "name" : "Сельское поселение", "short_name" : "с/п", "type" : "1"},
    {"id" : "23", "name" : "Аал", "short_name" : "аал", "type" : "1"},
    {"id" : "24", "name" : "Аул", "short_name" : "аул", "type" : "1"},
    {"id" : "25", "name" : "Выселки(ок)", "short_name" : "высел", "type" : "1"},
    {"id" : "26", "name" : "Деревня", "short_name" : "д.", "type" : "0"},
    {"id" : "27", "name" : "Железнодорожная будка", "short_name" : "ж/д будка", "type" : "0"},
    {"id" : "28", "name" : "Железнодорожная казарма", "short_name" : "ж/д казарм", "type" : "0"},
    {"id" : "29", "name" : "ж/д останов. (обгонный) пункт", "short_name" : "ж/д оп.", "type" : "1"},
    {"id" : "30", "name" : "Железнодорожный пост", "short_name" : "ж/д пост.", "type" : "1"},
    {"id" : "31", "name" : "Железнодорожный разъезд", "short_name" : "ж/д рзд.", "type" : "1"},
    {"id" : "32", "name" : "Железнодорожная станция", "short_name" : "ж/д ст.", "type" : "0"},
    {"id" : "33", "name" : "Заимка", "short_name" : "заимка", "type" : "0"},
    {"id" : "34", "name" : "Казарма", "short_name" : "казарма", "type" : "0"},
    {"id" : "35", "name" : "Местечко", "short_name" : "м", "type" : "0"},
    {"id" : "36", "name" : "Микрорайон", "short_name" : "мкр.", "type" : "1"},
    {"id" : "37", "name" : "Населенный пункт", "short_name" : "нп.", "type" : "1"},
    {"id" : "38", "name" : "Остров", "short_name" : "остров", "type" : "0"},
    {"id" : "39", "name" : "Поселок", "short_name" : "п.", "type" : "0"},
    {"id" : "40", "name" : "Планировочный район", "short_name" : "п/р", "type" : "0"},
    {"id" : "41", "name" : "Поселок и(при) станция(и)", "short_name" : "п/ст", "type" : "0"},
    {"id" : "42", "name" : "Починок", "short_name" : "починок", "type" : "0"},
    {"id" : "43", "name" : "Промышленная зона", "short_name" : "промзона", "type" : "1"},
    {"id" : "44", "name" : "Разъезд", "short_name" : "рзд.", "type" : "1"},
    {"id" : "45", "name" : "Село", "short_name" : "с", "type" : "0"},
    {"id" : "46", "name" : "Слобода", "short_name" : "сл.", "type" : "1"},
    {"id" : "47", "name" : "Станция", "short_name" : "ст.", "type" : "0"},
    {"id" : "48", "name" : "Станица", "short_name" : "ст-ца", "type" : "0"},
    {"id" : "49", "name" : "Хутор", "short_name" : "х", "type" : "0"},
    {"id" : "50", "name" : "Городок", "short_name" : "городок", "type" : "0"},
    {"id" : "51", "name" : "Железнодорожная платформа", "short_name" : "ж/д платф", "type" : "0"},
    {"id" : "52", "name" : "Квартал", "short_name" : "кв-л", "type" : "0"},
    {"id" : "53", "name" : "Арбан", "short_name" : "арбан", "type" : "0"},
    {"id" : "54", "name" : "Садовое неком-е товарищество", "short_name" : "снт", "type" : "0"},
    {"id" : "55", "name" : "Леспромхоз", "short_name" : "лпх", "type" : "0"},
    {"id" : "56", "name" : "Погост", "short_name" : "погост", "type" : "1"},
    {"id" : "57", "name" : "Кордон", "short_name" : "кордон", "type" : "1"},
    {"id" : "58", "name" : "Аллея", "short_name" : "аллея", "type" : "1"},
    {"id" : "59", "name" : "Бульвар", "short_name" : "б-р", "type" : "0"},
    {"id" : "60", "name" : "Въезд", "short_name" : "въезд", "type" : "1"},
    {"id" : "61", "name" : "Дорога", "short_name" : "дор", "type" : "1"},
    {"id" : "62", "name" : "Животноводческая точка", "short_name" : "жт", "type" : "1"},
    {"id" : "63", "name" : "Заезд", "short_name" : "заезд", "type" : "1"},
    {"id" : "64", "name" : "Километр", "short_name" : "км", "type" : "1"},
    {"id" : "65", "name" : "Кольцо", "short_name" : "кольцо", "type" : "1"},
    {"id" : "66", "name" : "Линия", "short_name" : "линия", "type" : "1"},
    {"id" : "67", "name" : "Набережная", "short_name" : "наб", "type" : "1"},
    {"id" : "68", "name" : "Парк", "short_name" : "парк", "type" : "0"},
    {"id" : "69", "name" : "Переулок", "short_name" : "пер", "type" : "1"},
    {"id" : "70", "name" : "Переезд", "short_name" : "переезд", "type" : "1"},
    {"id" : "71", "name" : "Площадь", "short_name" : "пл.", "type" : "0"},
    {"id" : "72", "name" : "Площадка", "short_name" : "пл-ка", "type" : "1"},
    {"id" : "73", "name" : "Проезд", "short_name" : "проезд", "type" : "1"},
    {"id" : "74", "name" : "Проспект", "short_name" : "пр-кт", "type" : "1"},
    {"id" : "75", "name" : "Просек", "short_name" : "просек", "type" : "0"},
    {"id" : "76", "name" : "Проселок", "short_name" : "проселок", "type" : "1"},
    {"id" : "77", "name" : "Проулок", "short_name" : "проулок", "type" : "1"},
    {"id" : "78", "name" : "Сад", "short_name" : "сад", "type" : "1"},
    {"id" : "79", "name" : "Сквер", "short_name" : "сквер", "type" : "1"},
    {"id" : "80", "name" : "Строение", "short_name" : "стр.", "type" : "0"},
    {"id" : "81", "name" : "Тракт", "short_name" : "тракт", "type" : "1"},
    {"id" : "82", "name" : "Тупик", "short_name" : "туп", "type" : "1"},
    {"id" : "83", "name" : "Участок", "short_name" : "уч-к", "type" : "1"},
    {"id" : "84", "name" : "Шоссе", "short_name" : "ш", "type" : "1"},
    {"id" : "85", "name" : "Платформа", "short_name" : "платф", "type" : "0"},
    {"id" : "86", "name" : "Полустанок", "short_name" : "полустанок", "type" : "1"},
    {"id" : "87", "name" : "Спуск", "short_name" : "спуск", "type" : "1"},
    {"id" : "88", "name" : "Канал", "short_name" : "канал", "type" : "1"},
    {"id" : "89", "name" : "Гаражно-строительный кооператив", "short_name" : "гск", "type" : "0"},
    {"id" : "90", "name" : "Проток", "short_name" : "проток", "type" : "0"},
    {"id" : "91", "name" : "Коса", "short_name" : "коса", "type" : "1"},
    {"id" : "92", "name" : "Вал", "short_name" : "вал", "type" : "1"},
    {"id" : "93", "name" : "Ферма", "short_name" : "ферма", "type" : "0"},
    {"id" : "94", "name" : "Мост", "short_name" : "мост", "type" : "1"},
    {"id" : "95", "name" : "Автономная республика", "short_name" : "АР", "type" : "0"},
    {"id" : "96", "name" : "Пляж", "short_name" : "пляж", "type" : "1"},
    {"id" : "97", "name" : "Бухта", "short_name" : "бухта", "type" : "1"},
    {"id" : "98", "name" : "Кооператив", "short_name" : "кооп", "type" : "0"},
    {"id" : "99", "name" : "Причал", "short_name" : "прич", "type" : "1"},
    {"id" : "100", "name" : "Жилищный массив", "short_name" : "ж/м", "type" : "0"}
];


function getLocation () {
    var sResult = 'крупнейшие провайдеры региона',
        o = null;
    if (typeof region_hierarchy !== "undefined") {
        for (var i = 0, l = region_hierarchy.length; i < l; i++) {
            if (region_hierarchy[i]["regUICalculatedBy"] == "1") {
                o = aObjectType[parseInt(region_hierarchy[i]["type"], 10)];
                sResult = (sResult == 'крупнейшие провайдеры региона') ? sResult = 'крупнейшие провайдеры ' : sResult += ' ';
                sResult += (o["type"] == "0") ? (o["short_name"] + ' ' + region_hierarchy[i]["name"]) : (region_hierarchy[i]["name"] + ' ' + o["short_name"]);
                //break;
            }
        }
    }
    return sResult;
}